### ISSUE TITLE
Memory free issue with multiprocessing

### ISSUE THREAD

**Issue by ltetrel** [SIMEXP/DeepNeuroAN#1]
There is a bug when freeing the shared memory. Python is waiting for worker to free the memory.

```
  File "/DeepNeuroAN/deepneuroan/train.py", line 449, in <module>
    main()
  File "/DeepNeuroAN/deepneuroan/train.py", line 445, in main
    train_gen.run()
  File "/DeepNeuroAN/deepneuroan/train.py", line 246, in run
    , use_multiprocessing=False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1303, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 221, in model_iteration
    batch_data = _get_next_batch(generator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 363, in _get_next_batch
    generator_output = next(generator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/data_utils.py", line 779, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 638, in get
    self.wait(timeout)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 635, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
  File "/usr/lib/python3.6/multiprocessing/heap.py", line 208, in free
```

**Comment by ltetrel** [comment]
`free` from `/usr/lib/python3.6/multiprocessing/heap.py`
```
def free(self, block):
    199         # free a block returned by malloc()
    200         # Since free() can be called asynchronously by the GC, it could happen
    201         # that it's called while self._lock is held: in that case,
    202         # self._lock.acquire() would deadlock (issue #12352). To avoid that, a
    203         # trylock is used instead, and if the lock can't be acquired
    204         # immediately, the block is added to a list of blocks to be freed
    205         # synchronously sometimes later from malloc() or free(), by calling
    206         # _free_pending_blocks() (appending and retrieving from a list is not
    207         # strictly thread-safe but under cPython it's atomic thanks to the GIL).
    208         assert os.getpid() == self._lastpid
    209         if not self._lock.acquire(False):
    210             # can't acquire the lock right now, add the block to the list of
    211             # pending blocks to free
    212             self._pending_free_blocks.append(block)
    213         else:
    214             # we hold the lock
    215             try:
    216                 self._free_pending_blocks()
    217                 self._allocated_blocks.remove(block)
    218                 self._free(block)
    219             finally:
    220                 self._lock.release()
